### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by LuizStSantos** [futzu/umzz#13]
I have a problem and I can't run it yesterday it was working normally, then I went to install it on another server and it didn't want to work anymore

```
root@srv-playout:/home/luiz# umzz -i /usr/share/ffplayout/public/live/master.m3u8 -d -l -n
input = /usr/share/ffplayout/public/live/master.m3u8
byterange = False
continue_m3u8 = False
delete = True
live = True
no_discontinuity = True
no_throttle = False
output_dir = .
program_date_time = False
replay = False
sidecar_file = None
shulga = False
time = 2
hls_tag = x_cue
window_size = 5
version = False
{
   "lines": [
      "#EXT-X-STREAM-INF:BANDWIDTH=3660800,RESOLUTION=1920x1080,CODECS=\"avc1.4d4029,mp4a.40.2\"",
      "stream_1080p.m3u8"
   ],
   "media": "/usr/share/ffplayout/public/live/stream_1080p.m3u8",
   "tags": {
      "#EXT-X-STREAM-INF": {
         "CODECS": "avc1.4d4029,mp4a.40.2",
         "RESOLUTION": "1920x1080",
         "BANDWIDTH": 3660800
      }
   },
   "base_uri": "/usr/share/ffplayout/public/live/",
   "relative_uri": "stream_1080p.m3u8"
}
Traceback (most recent call last):
  File "/usr/local/bin/umzz", line 5, in <module>
    cli()
  File "/usr/local/lib/pypy3.9/dist-packages/umzz.py", line 207, in cli
    do(args)
  File "/usr/local/lib/pypy3.9/dist-packages/umzz.py", line 187, in do
    fu.decode()
  File "/usr/local/lib/pypy3.9/dist-packages/m3ufu.py", line 639, in decode
    if not self._parse_line(line):
  File "/usr/local/lib/pypy3.9/dist-packages/m3ufu.py", line 620, in _parse_line
    self._do_media(line)
  File "/usr/local/lib/pypy3.9/dist-packages/m3ufu.py", line 586, in _do_media
    self._add_media(media)
  File "/usr/local/lib/pypy3.9/dist-packages/m3ufu.py", line 563, in _add_media
    segment.decode()
  File "/usr/local/lib/pypy3.9/dist-packages/m3ufu.py", line 396, in decode
    self.tags = TagParser(self.lines).tags
  File "/usr/local/lib/pypy3.9/dist-packages/m3ufu.py", line 141, in __init__
    self._parse_tags(line)
  File "/usr/local/lib/pypy3.9/dist-packages/m3ufu.py", line 159, in _parse_tags
    if line[0] !='#':

``` 
```
cat /usr/share/ffplayout/public/live/master.m3u8
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:BANDWIDTH=6740800,RESOLUTION=1920x1080,CODECS="avc1.4d4029,mp4a.40.2"
stream_1080p.m3u8

#EXT-X-STREAM-INF:BANDWIDTH=3405600,RESOLUTION=1280x720,CODECS="avc1.4d4029,mp4a.40.2"
stream_720p.m3u8

#EXT-X-STREAM-INF:BANDWIDTH=1720400,RESOLUTION=960x540,CODECS="avc1.4d4029,mp4a.40.2"
stream_540p.m3u8

#EXT-X-STREAM-INF:BANDWIDTH=585200,RESOLUTION=640x360,CODECS="avc1.4d4029,mp4a.40.2"
stream_360p.m3u8


``` 

```
-c:v h264_nvenc
-r:v 25
-aspect 16:9
-level 41
-colorspace:v bt709 
-color_primaries:v bt709 
-color_trc:v bt709 
-color_range:v tv
-delay 0
-c:a aac
-ar 48000
-profile:v main
-g 25
-filter_complex "[0:v]split=4[v1_out][v2_out][v3_out][v4_out]; [v1_out]scale=w=1920:h=1080[v1_out_final]; [v2_out]scale=w=1280:h=720[v2_out_final]; [v3_out]scale=w=960:h=540[v3_out_final]; [v4_out]scale=w=640:h=360[v4_out_final]; [0:a]asplit=4[a1][a2][a3][a4]"
-map "[v1_out_final]"
-map "[a1]"
-b:v:0 6000k
-maxrate:0 6500k
-bufsize:0 6600k
-b:a:0 128k
-map "[v2_out_final]"
-map "[a2]"
-b:v:1 3000k
-maxrate:1 3500k
-bufsize:1 3600k
-b:a:1 96k
-map "[v3_out_final]"
-map "[a3]"
-b:v:2 1500k
-maxrate:2 2000k
-bufsize:2 2100k
-b:a:2 64k
-map "[v4_out_final]"
-map "[a4]"
-b:v:3 500k
-maxrate:3 1000k
-bufsize:3 1100k
-b:a:3 32k
-hls_flags append_list+delete_segments+omit_endlist
-hls_segment_filename /usr/share/ffplayout/public/live/stream_%v-%d.ts
-master_pl_name master.m3u8
-var_stream_map "v:0,a:0,name:1080p v:1,a:1,name:720p v:2,a:2,name:540p v:3,a:3,name:360p"
-metadata:s:a language=pt  -metadata service_name="Canal Solo Fértil" -metadata service_name="Canal Solo Fértil"  -metadata network_name="Canal Solo Fértil" /usr/share/ffplayout/public/live/stream_%v.m3u8
```

**Comment by futzu** [comment]
I think I just fixed that.

**Comment by futzu** [comment]
it's should be in m3ufu 0.0.89.
https://github.com/futzu/m3ufu/commit/4c659bc5cca86f83944be9ad80e53ec6e8e71100

let me know if it isn't.

I have a new repo https://github.com/futzu/np, that's what umzz is going to be on the next release, I am squashing the last few small bugs now. It is sooo much faster and easier.
